version: '3.8'

services:
  app:
    env_file: .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    command: npm run start:dev